---
title: "COVID-19 by Week Age/Sex"
author: "David Jackson"
date: "9/13/2020"
output: 
  html_document: 
    fig_height: 7
    fig_width: 9
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
theme_set(theme_linedraw())
```

## R Markdown

```{r}
rm(list=ls())
df <- read.csv("./DATA/covid-sex-age.csv")
# df <- df[c(:8)]
colnames(df) <- c("Date","sex","Age","Deaths","Covid")
df$Ymd <- substr(df$Date,1,10)
df$Ymd <- as.Date(df$Date,format="%Y-%m-%d")
summary(df$Deaths)
summary(df$Covid)
```
```{r}
All <- subset(df,Age =="All ages")
not_all <- subset(df,Age !="All ages")
```

```{r}
not_age_week <- aggregate(Covid~Age+Ymd,data=not_all,FUN=sum)
not_age_week <- subset(not_age_week,Ymd >="2020-06-01")
```

### Plot of COVID-19 Deaths by Age Group

```{r}
ggplot(not_age_week) +geom_line(aes(x=Ymd,y=Covid,col=Age)) +
  scale_x_date(date_breaks = "2 week") +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Plot of COVID-19 Deaths by Age Group",
       x="Date",y="Covid-19 Deaths",
       caption = "(Source: US CDC)")

```
```{r}
mydata = subset(not_age_week,Age %in% c("65-74 years","75-84 years","85 years and over"))
```

# Plots by Selected Age Groups: 65 - 85 Year of Age

```{r}
ggplot(mydata) +geom_line(aes(x=Ymd,y=Covid,col=Age)) +
  scale_x_date(date_breaks = "2 week") +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title="Plot of COVID-19 Deaths for Ages 64 and Over",
       x="Date",y="Covid-19 Deaths",
       caption = "(Source: US CDC)")

```
```{r}
Sept4 <- subset(not_age_week,Ymd >="2020-09-11")
ggplot(Sept4) + geom_col(aes(x=Age,y=Covid)) +
  theme(axis.text.x = element_text(angle = 45)) +
  labs(title = "Total Deaths by Age Group",
  subtitle="for Week ending  - Sept. 19", caption = "(Source US CDC)"
  )

```
```{r}
AA <- subset(not_all,sex !="All Sex")
```
```{r}
AB <- aggregate(Covid~sex+Ymd,data=AA,FUN=sum)
ggplot(AB,aes(x=Ymd,y=Covid,fill=sex))  + 
  labs(title="Comparing Male and Female COVI-19 Deaths by Month") +
   geom_bar(stat = "identity", position = 'dodge')
```
```{r}
AC <- aggregate(Covid~sex,data=AA,FUN=sum)
```

