---
title: "Total Covidi19 Deaths by Age and Sex"
author: "David Jackson"
date: "2021/01/24 6:30 PM/EST, 2021"
output: 
  html_document: 
    fig_width: 10
    fig_height: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,error = FALSE)
library(ggplot2)
library(plotly)
library(scales)
library(dplyr)
library(tidyr)
library(readr)
library(janitor)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))
```
```{r}
rm(list=ls())
WeeklyAge <- read_csv("./DATA/Weekly_by_Sex__Age.csv") %>%
select(- 'MMWR Week')

colnames(WeeklyAge) <- c("Date","State","EndDate","Sex","Age","Total","COVID19")
str(WeeklyAge)
```
```{r}
WeeklyAge$Date <- gsub("/","-",WeeklyAge$Date)
WeeklyAge$Date <- as.Date(WeeklyAge$Date,format="%m-%d-%Y")
WeeklyAge$EndDate <- gsub("/","-",WeeklyAge$EndDate)
WeeklyAge$EndDate <- as.Date(WeeklyAge$EndDate,format="%m-%d-%Y")
```

### Total Covidi19 Deaths by Age and Sex
#### Source: US Center for Disease  Control and Prevention
####  All Ages by Date

```{r}
all_age <- subset(WeeklyAge,Age !="All Ages" & Sex=="All Sex")
``` 

```{r}
sex_totals <-subset(WeeklyAge,Age !="All Ages" & Sex !="All Sex")
ggplot(sex_totals) + geom_col(aes(x=Sex,y=COVID19)) +
  labs(title="Total Deaths by Sex",subtitle="(As of Jan. 30, 2020)",
       caption="[Source: http://www.cdc.gov]") +
  scale_y_continuous(labels = comma)

```
```{r}
ggplot(all_age) + geom_col(aes(x=reorder(Age,COVID19),y=COVID19)) + coord_flip() +
  labs(title="Total COVID19 Deaths by Age Group",caption="(Source http://www.cdc.gov)") +
  scale_y_continuous(labels=comma)
```

### Total Deaths and Percentage of Deaths by Age Group

```{r}
CDCAge <- data.table::fread("./DATA/State_by_Sex__Age.csv")
CDCAge <- CDCAge %>%janitor::clean_names() %>%
  select(end_date,state,sex,age_group,covid_19_deaths,
        total_deaths,pneumonia_deaths,influenza_deaths )

```
```{r}
CDCAge$end_date <- gsub("/","-",CDCAge$end_date)
CDCAge$end_date <- as.Date(CDCAge$end_date,format="%m-%d-%Y")
```
```{r}
CDCAge %>% filter(age_group != "All Ages" & sex != "All") %>% na.omit() %>%
ggplot() + geom_col(aes(x=age_group,y=total_deaths/sum(total_deaths,na.rm=TRUE))) +
  theme(axis.text.x = element_text(angle = 45)) + 
  scale_y_continuous(labels=percent) + coord_flip() +
  labs(title="Deaths by Age Group as Percentage",x="Age Group",y="% of Age",
       caption="(Source http://www.cdc.gov)") 
```

```{r}
all_sex <- subset(WeeklyAge,Age !="All Ages")
ggplot(all_sex) + geom_col(aes(x=reorder(Age,COVID19),y=COVID19)) + coord_flip() +
  labs(title="Total COVID19 Deaths by Age Group and Sex",
       caption="(Source http://www.cdc.gov") +
  facet_wrap(~Sex) + theme(axis.text.x = element_text(angle = 90))
  
```
```{r}
not_all_ages <- subset(all_sex, Age %in% c("55-64 Years","65-74 Years",
                "75-84 Years","85 Years and Over") & Date >="2020-03-01")
```
```{r}
ggplot(not_all_ages) + geom_line(aes(x=EndDate,y=COVID19,col="Deaths")) + facet_wrap(~Age,ncol=2) +
  labs(title="COVID19 Deaths by Week for Age Groups >= 55",
       caption="(Source http://cdc.gov)") +
  geom_smooth(aes(x=EndDate,y=COVID19,col="Loess"),span=0.25)
  
```

```{r}
# CDCAge %>% filter(age_group != "All Ages" & sex != "All") %>%
# ggplot() + geom_col(aes(x=age_group,y=total_deaths)) +
#   theme(axis.text.x = element_text(angle = 45)) +
#   labs(title="Total Deaths by Age Group",x="Age Group",y="Total Deaths") +
#   scale_y_continuous(labels = scales::comma)
#   
  
```
`
#### COVID-19 Deaths as a Precent of All Deaths 

```{r}
all_all <- subset(WeeklyAge,Age =="All Ages" & Sex=="All Sex")
all_all$Percent <- all_all$COVID19/all_all$Total
```
```{r}
ggplot(all_all) + geom_line(aes(x=EndDate,y=Percent),col="red") +
  scale_y_continuous(labels=percent) +
  labs(title="CovID-19 Deaths As a Percent of Total Deaths",y="Percent of Total Deaths",caption="[Source: http://cdc.gov]")
  
```

#### Plot of Both Total Deaths and COVID19 Deaths
* Heart disease: 655,381.
* Cancer: 599,274.
* 350,186 (US COVID19 Deaths as of Nov. 1, 2020)

```{r}
ggplot(all_all) + geom_line(aes(x=EndDate,y=Total,col="Total Deaths")) +
  geom_line(aes(x=EndDate,y=COVID19,col="COVID19 Deaths")) +
  labs(title="Weekly: Total Deaths and COVID19 Deaths",
       caption="[Source: http://cdc.gov]",y="Weekly Deaths (Log10)") +
  scale_y_log10() + scale_y_continuous(labels=comma)

ggplot(all_all) + geom_line(aes(x=EndDate,y=Total,col="Total Deaths")) +
  geom_line(aes(x=EndDate,y=COVID19,col="COVID19 Deaths")) +
  labs(title="Weekly: Total Deaths and COVID19 Deaths",
       caption="[Source: http://cdc.gov]")
  
```
```{r}
not_all_ages <- subset(all_sex, Age %in% c("5-14 Years","15-24 Years","25-34 Years","35-44 Years","45-54 eYars") & EndDate >="2020-03-01")
```
```{r}
ggplot(not_all_ages) + geom_line(aes(x=EndDate,y=COVID19,col="Deaths")) + facet_wrap(~Age,ncol=2) +
  labs(title="COVID19 Deaths by Week for Age Groups =< 55",
       caption="(Source http://cdc.gov)") +
  geom_smooth(aes(x=EndDate,y=COVID19,col="Loess"),span=0.25) 
  
  
```

#### Deaths for Last Seven Days

```{r}
all_age %>% filter(EndDate >="2021-01-30") %>%
ggplot() + geom_col(aes(x=reorder(Age,COVID19),y=COVID19)) + coord_flip() +
  labs(title="Total COVID19 Deaths by Age Group",subtitle="(Date >=2021-01-30)"
       ,caption="(Source http://www.cdc.gov)")
```




