---
title: "Pneumonia Deaths"
author: "David Jackson"
date: "1/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(dplyr)
library(tidyr)
library(readr)
library(janitor)
```

## Historical Pneumonia Deaths (Our World In Data)

```{r}
df <- read_csv("./DATA/pneumonia.csv")  %>% filter(Code =="USA")

df <- clean_names(df)
colnames(df) <- c("County","ID","Year","ages_under_5","ages_5_14",
                  "ages_15_49","ages_50_69","ages_70")
```

## Plot Total Pneumonia Deaths by Year

```{r}
attach(df)
df$TotalDeaths <- ages_under_5 + ages_5_14 + ages_15_49 + ages_50_69 + ages_70

```
```{r}
df %>% ggplot() + geom_col(aes(x=Year,y=TotalDeaths)) + 
  labs(title = "Pneumonia Lower respiratory infections Deaths by Year")

  
```
```{r}
age_groups <- df %>% pivot_longer(col=starts_with("ages_"),values_to = "Deaths")
```
```{r}
age_groups %>% ggplot(aes(x=name,y=Deaths)) + geom_col() +
  facet_wrap(~Year) + theme(axis.text.x = element_text(angle = 90))
```



