---
title: 'US COVID-19 by Age Groups'
author: "David J Jackson"
date: "June 29, 2020 16:25 UD/UT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(scales)
library(lubridate)
```
```{r}
rm(list=ls())
CDCAge <- data.table::fread("DATA/COVID-19_Death_Counts.csv")
CDCAge <- janitor::clean_names(CDCAge)
CDCAge$data_as_of <- mdy(CDCAge$data_as_of)
CDCAge$start_week <- mdy(CDCAge$start_week)
CDCAge$end_week <- mdy(CDCAge$end_week)
```
```{r}
CDCAge %>% filter(age_group != "All ages" & sex != "All") %>%
ggplot() + geom_col(aes(x=age_group,y=total_deaths)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title="Total Deaths by Age Group",x="Age Group",y="Total Deaths") 
  
```
```{r}
CDCAge %>% filter(age_group != "All ages" & sex != "All") %>%
ggplot() + geom_col(aes(x=age_group,y=total_deaths/sum(total_deaths,na.rm=TRUE))) +
  theme(axis.text.x = element_text(angle = 90)) + 
  scale_y_continuous(labels=percent) +
  labs(title="Deaths by Age Group as Percentage",x="Age Group",y="% of Age")
```

